---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Get response from API
      uri:
        url: "{{ api_url }}?output={{ output }}&search={{ mac }}"
        status_code: 200
        return_content: yes
        headers:
          X-Authentication-Token: "{{ api_key }}"
      register: api_response

    - name: Show MAC manufacturer
      debug:
        msg: "{{ api_response.content }}"